version: "3"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
      - "127.0.0.1:443:443" # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      DEBUG: "${DEBUG-}"
      LS_LOG: "error"
      ENVIRONMENT: "test"
      DYNAMODB_SHARE_DB: 1
      DYNAMODB_IN_MEMORY: 1
    env_file:
      - .env.test
    healthcheck:
      test: [
        "CMD",
        "sh",
        "-c",
        "awslocal dynamodb list-tables && awslocal secretsmanager list-secrets"
      ]
      timeout: 60s
      interval: 5s
      retries: 15

  cargo-lambda:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.watch
    ports:
      - 9000:9000
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 9000"]
      timeout: 10s
      interval: 5s
      retries: 15
    env_file:
      - .env.test
    profiles: ["tests"]
    depends_on:
      localstack:
        condition: service_healthy

  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - 8545:8545
    command: -m "siren differ mirror vapor soap child round business defy robot fiscal village" -q
    profiles: ["local_tests", "tests"]
    healthcheck:
      test: [
        "CMD",
        "node",
        "/app/dist/node/cli.js",
        "instances",
        "list"
      ]
      interval: 5s
      timeout: 5s
      retries: 5

  wiremock:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.wiremock
    profiles: ["local_tests", "tests"]
    environment:
      PORT: 3000
    ports:
      - 3000:3000

  tests:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.tests
    env_file:
      - .env.test
    profiles: ["tests"]
    depends_on:
      localstack:
        condition: service_healthy
      cargo-lambda:
        condition: service_healthy
      ganache:
        condition: service_healthy
      wiremock:
        condition: service_started

  dynamodb-admin:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.dynamoadmin
    environment:
      DYNAMO_ENDPOINT: "http://localstack:4566"
      DYNAMO_PORT: 4000
    profiles: ["local"]
    ports:
      - 4000:4000
    depends_on:
      localstack:
        condition: service_healthy
