# We build our own image since our harness pipeline does not support using volumes and we need to copy the mappings.

FROM wiremock/wiremock:latest

ENV PORT=

EXPOSE ${PORT}

# copy wiremock mappings (mocks)
COPY ../tests/wiremock /home/wiremock

ENTRYPOINT "/docker-entrypoint.sh" "--port" "$PORT"
